import type { BibleBookId } from '@/lib/scripture';

export type BibleBookMeta = {
  id: BibleBookId;
  slug: string; // Slug matches the canonical folder name from wldeh/bible-api (all lowercase).
  chapters: number;
};

export const BIBLE_BOOKS: BibleBookMeta[] = [
  { id: 'Genesis', slug: 'genesis', chapters: 50 },
  { id: 'Exodus', slug: 'exodus', chapters: 40 },
  { id: 'Leviticus', slug: 'leviticus', chapters: 27 },
  { id: 'Numbers', slug: 'numbers', chapters: 36 },
  { id: 'Deuteronomy', slug: 'deuteronomy', chapters: 34 },
  { id: 'Joshua', slug: 'joshua', chapters: 24 },
  { id: 'Judges', slug: 'judges', chapters: 21 },
  { id: 'Ruth', slug: 'ruth', chapters: 4 },
  { id: '1 Samuel', slug: '1-samuel', chapters: 31 },
  { id: '2 Samuel', slug: '2-samuel', chapters: 24 },
  { id: '1 Kings', slug: '1-kings', chapters: 22 },
  { id: '2 Kings', slug: '2-kings', chapters: 25 },
  { id: '1 Chronicles', slug: '1-chronicles', chapters: 29 },
  { id: '2 Chronicles', slug: '2-chronicles', chapters: 36 },
  { id: 'Ezra', slug: 'ezra', chapters: 10 },
  { id: 'Nehemiah', slug: 'nehemiah', chapters: 13 },
  { id: 'Esther', slug: 'esther', chapters: 10 },
  { id: 'Job', slug: 'job', chapters: 42 },
  { id: 'Psalms', slug: 'psalms', chapters: 150 },
  { id: 'Proverbs', slug: 'proverbs', chapters: 31 },
  { id: 'Ecclesiastes', slug: 'ecclesiastes', chapters: 12 },
  { id: 'Song of Solomon', slug: 'song-of-solomon', chapters: 8 },
  { id: 'Isaiah', slug: 'isaiah', chapters: 66 },
  { id: 'Jeremiah', slug: 'jeremiah', chapters: 52 },
  { id: 'Lamentations', slug: 'lamentations', chapters: 5 },
  { id: 'Ezekiel', slug: 'ezekiel', chapters: 48 },
  { id: 'Daniel', slug: 'daniel', chapters: 12 },
  { id: 'Hosea', slug: 'hosea', chapters: 14 },
  { id: 'Joel', slug: 'joel', chapters: 3 },
  { id: 'Amos', slug: 'amos', chapters: 9 },
  { id: 'Obadiah', slug: 'obadiah', chapters: 1 },
  { id: 'Jonah', slug: 'jonah', chapters: 4 },
  { id: 'Micah', slug: 'micah', chapters: 7 },
  { id: 'Nahum', slug: 'nahum', chapters: 3 },
  { id: 'Habakkuk', slug: 'habakkuk', chapters: 3 },
  { id: 'Zephaniah', slug: 'zephaniah', chapters: 3 },
  { id: 'Haggai', slug: 'haggai', chapters: 2 },
  { id: 'Zechariah', slug: 'zechariah', chapters: 14 },
  { id: 'Malachi', slug: 'malachi', chapters: 4 },
  { id: 'Matthew', slug: 'matthew', chapters: 28 },
  { id: 'Mark', slug: 'mark', chapters: 16 },
  { id: 'Luke', slug: 'luke', chapters: 24 },
  { id: 'John', slug: 'john', chapters: 21 },
  { id: 'Acts', slug: 'acts', chapters: 28 },
  { id: 'Romans', slug: 'romans', chapters: 16 },
  { id: '1 Corinthians', slug: '1-corinthians', chapters: 16 },
  { id: '2 Corinthians', slug: '2-corinthians', chapters: 13 },
  { id: 'Galatians', slug: 'galatians', chapters: 6 },
  { id: 'Ephesians', slug: 'ephesians', chapters: 6 },
  { id: 'Philippians', slug: 'philippians', chapters: 4 },
  { id: 'Colossians', slug: 'colossians', chapters: 4 },
  { id: '1 Thessalonians', slug: '1-thessalonians', chapters: 5 },
  { id: '2 Thessalonians', slug: '2-thessalonians', chapters: 3 },
  { id: '1 Timothy', slug: '1-timothy', chapters: 6 },
  { id: '2 Timothy', slug: '2-timothy', chapters: 4 },
  { id: 'Titus', slug: 'titus', chapters: 3 },
  { id: 'Philemon', slug: 'philemon', chapters: 1 },
  { id: 'Hebrews', slug: 'hebrews', chapters: 13 },
  { id: 'James', slug: 'james', chapters: 5 },
  { id: '1 Peter', slug: '1-peter', chapters: 5 },
  { id: '2 Peter', slug: '2-peter', chapters: 3 },
  { id: '1 John', slug: '1-john', chapters: 5 },
  { id: '2 John', slug: '2-john', chapters: 1 },
  { id: '3 John', slug: '3-john', chapters: 1 },
  { id: 'Jude', slug: 'jude', chapters: 1 },
  { id: 'Revelation', slug: 'revelation', chapters: 22 },
];

export function getBookBySlug(slug: string): BibleBookMeta | undefined {
  return BIBLE_BOOKS.find((book) => book.slug === slug);
}
